---
# tasks file for kerberos client role
- name: ensure kerberos client packages are installed
  yum:
    name: "{{ kerberos_client_packages }}"
    state: present

- name: ensure kdc server is in the hosts file
  lineinfile:
    path: /etc/hosts
    line: '{{ kerberos_client_kdc_ip }}	{{ kerberos_client_kdc_hostname }}	{{  kerberos_client_kdc_hostname.split(".")[0] | lower }}'
    state: present

- name: ensure the krb5.conf file is setup accordingly
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644