Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "kdc.lab.com"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.33.17"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "kdc"
    vb.cpus = 1
    vb.memory = 2048
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

end
