Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = 2048
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

  config.vm.define "kdc" do |kdc|
    kdc.vm.hostname = "kdc.lab.com"
    kdc.vm.network "private_network", ip: "192.168.33.20"
  end

  config.vm.define "client" do |clt|
    clt.vm.hostname = "client.lab.com"
    clt.vm.network "private_network", ip: "192.168.33.30"
  end

end